name: ci-test #これはgithub リポジトリのアクションページに表示される

on:  #このworkflowをトリガーするイベントを定義する
  push:
    branches: [ "main" ] #今回の場合mainブランチにpushされた時とpull_requestが作成された時
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Test
      run: make test
