name: ci-test #これはgithub リポジトリのアクションページに表示される

on:  #このworkflowをトリガーするイベントを定義する
  push:
    branches: [ "main" ] #今回の場合mainブランチにpushされた時とpull_requestが作成された時
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:  # PostgreSQL コンテナを設定
        image: postgres:12  # 使用する PostgreSQL のバージョンを指定
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:  # コンテナ内の環境変数
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple_bank

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Run migrations
      run: make migrateup    

    - name: Test
      run: make test
